steps:
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Apply Kubernetes configuration'
    args:
      - 'run'
      - '--filename=kubernetes/'
      - '--location=us-central1-a'
      - '--cluster=gcp-cicd-cluster'

options:
  logging: CLOUD_LOGGING_ONLY
