apiVersion: apps/v1
kind: Deployment

metadata:
  name: gcp-cicd-app

spec:
  replicas: 6

  selector:
    matchLabels:
      app: gcp-cicd-app

  template:
    metadata:
      labels:
        app: gcp-cicd-app

    spec:
      containers:
        - name: gcp-cicd-app
          image: us-central1-docker.pkg.dev/gcp-kubernetes-cicd-lab/gcp-cicd-images/gcp-cicd-app:v2

          ports:
            - containerPort: 8080

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
